import type { ProductFamily, ProductIndexItem } from '@/types/product';

export const products = [
  {
    id: 'my-dev-kit-ecosystem',
    slug: 'my-dev-kit',
    title: 'my-dev-kit Ecosystem',
    shortTitle: 'my-dev-kit',
    summary: 'A local-first toolkit that combines static repository evidence, workflow orchestration, browser/runtime evidence, and optional assurance for coding-agent development.',
    description:
      'my-dev-kit retrieves bounded static evidence from a codebase. my-dev-kit-orchestrator organizes staged prompts, artifacts, readiness checks, responsibility continuity, and correction routing without running the coding agent itself. An external human or coding agent edits the target source. my-frontend-observer captures and evaluates what the frontend actually rendered and returns bounded runtime evidence for review or correction. my-dev-kit-lab provides optional experiments, audits, security validation, and reporting. The tools compose explicitly rather than silently invoking one another.',
    status: 'active',
    category: 'developer-tooling',
    positioning: 'Local-first evidence and workflow infrastructure for disciplined AI-assisted software development.',
    primaryAudience: [
      'Developers using AI-assisted coding workflows',
      'Technical project maintainers',
      'Teams evaluating repeatable coding-agent practices',
    ],
    featured: true,
    displayPriority: 10,
    roadmapPlanned: true,
    links: [],
    modules: [
      {
        id: 'my-dev-kit',
        slug: 'my-dev-kit',
        title: 'my-dev-kit',
        packageName: '@dailephd/my-dev-kit',
        roleLabel: 'Codebase Intelligence',
        layerLabel: 'Static repository evidence',
        summary: 'Local-first indexing and graph-guided retrieval of bounded codebase evidence.',
        description:
          'Indexes supported source structures and exposes search, exact lookup, graph slices, bounded source, role-aware context, graph diff, and conservative frontend and Android static evidence. Static evidence is not runtime proof.',
        status: 'active',
        stage: 'foundation',
        stack: ['TypeScript', 'Node.js', 'Static analysis', 'Graph-guided retrieval'],
        displayPriority: 10,
        links: [
          { id: 'my-dev-kit-module-repository', label: 'GitHub', href: 'https://github.com/dailephd/my-dev-kit', kind: 'repository', external: true },
          { id: 'my-dev-kit-module-package', label: 'npm', href: 'https://www.npmjs.com/package/@dailephd/my-dev-kit', kind: 'package', external: true },
        ],
        versionRoadmap: [
          { state: 'recent', version: '1.12.4', description: 'Core indexing and retrieval of supported `.test.` and `.spec.` files beneath selected source roots.' },
          { state: 'current', version: '1.12.5', description: 'Adds affected-neighborhood incremental refresh with trusted-baseline selection and explicit fallback evidence.' },
          { state: 'next', version: '1.13.0', description: 'Planned Android retrieval benchmarks, examples, and workflow documentation.' },
        ],
      },
      {
        id: 'my-dev-kit-orchestrator',
        slug: 'my-dev-kit-orchestrator',
        title: 'my-dev-kit-orchestrator',
        packageName: '@dailephd/my-dev-kit-orchestrator',
        repoName: 'my-dev-kit-orchestrator',
        roleLabel: 'Workflow Orchestration',
        layerLabel: 'Lifecycle, readiness, and correction control',
        summary: 'CLI-first staged workflow control for design-first coding-agent development.',
        description:
          'Generates bounded stage prompts, tracks artifacts and readiness, preserves Semantic Continuity, routes judge findings to correction stages, derives workflow-economics evidence, and exports handoffs. It does not execute coding agents or automatically run other ecosystem tools.',
        status: 'active',
        stage: 'prototype',
        stack: ['TypeScript', 'Node.js', 'Workflow orchestration', 'Coding-agent lifecycle'],
        displayPriority: 20,
        links: [
          { id: 'my-dev-kit-orchestrator-module-repository', label: 'GitHub', href: 'https://github.com/dailephd/my-dev-kit-orchestrator', kind: 'repository', external: true },
          { id: 'my-dev-kit-orchestrator-module-package', label: 'npm', href: 'https://www.npmjs.com/package/@dailephd/my-dev-kit-orchestrator', kind: 'package', external: true },
        ],
        versionRoadmap: [
          { state: 'recent', version: '1.5.0', description: 'Added Semantic Continuity so stable test responsibilities remain traceable through implementation, testing, verification, and correction.' },
          { state: 'current', version: '1.6.0', description: 'Adds versioned run telemetry and deterministic Workflow Economics without changing lifecycle or readiness decisions.' },
          { state: 'next', version: '1.7.0', description: "Planned Generic Ecosystem Evidence Intake using typed evidence requirements and references while preserving native producer contracts." },
        ],
      },
      {
        id: 'my-frontend-observer',
        slug: 'my-frontend-observer',
        title: 'my-frontend-observer',
        packageName: '@dailephd/my-frontend-observer',
        repoName: 'my-frontend-observer',
        roleLabel: 'Runtime Evidence',
        layerLabel: 'Browser observation and visual acceptance',
        summary: 'Local-first browser/runtime evidence for frontend changes, comparisons, contracts, references, and correction workflows.',
        description:
          'Captures rendered Chromium evidence, compares baselines and candidates, evaluates protected and preserved frontend contracts and reference fidelity, supports local viewer and annotation workflows, and returns bounded runtime evidence. It never edits target source.',
        status: 'active',
        stage: 'validation',
        stack: ['TypeScript', 'Playwright', 'React', 'Runtime evidence'],
        displayPriority: 30,
        links: [
          { id: 'my-frontend-observer-module-repository', label: 'GitHub', href: 'https://github.com/dailephd/my-frontend-observer', kind: 'repository', external: true },
          { id: 'my-frontend-observer-module-package', label: 'npm', href: 'https://www.npmjs.com/package/@dailephd/my-frontend-observer', kind: 'package', external: true },
        ],
        versionRoadmap: [
          { state: 'recent', version: '0.9.1', description: 'Hardened the PWA acceptance gate so offline and stale-evidence safety checks are independently reproducible.' },
          { state: 'current', version: '0.10.0', description: 'Completes the visual human–LLM frontend-change workflow across runtime capture, references, contracts, annotation, correction, and approval.' },
          { state: 'next', version: '0.11.0', description: 'Planned bounded runtime diagnostics for console errors, page errors, transport failures, and HTTP status evidence.' },
        ],
      },
      {
        id: 'my-dev-kit-lab',
        slug: 'my-dev-kit-lab',
        title: 'my-dev-kit-lab',
        packageName: '@dailephd/my-dev-kit-lab',
        repoName: 'my-dev-kit-lab',
        roleLabel: 'Validation Lab',
        layerLabel: 'Optional experiments and assurance',
        summary: 'Evidence-first experiments, audits, security validation, benchmarks, and reporting for the ecosystem and target projects.',
        description:
          'Measures context strategies, warm-index behavior, freshness and staleness through bounded experiments; runs supported code-rot, security, and Android checks; and produces reports, plots, galleries, and tutorials. It is optional for ordinary edits and does not guarantee token savings.',
        status: 'active',
        stage: 'validation',
        stack: ['TypeScript', 'Evaluation tooling', 'Security validation', 'Benchmarking'],
        displayPriority: 40,
        links: [
          { id: 'my-dev-kit-lab-module-repository', label: 'GitHub', href: 'https://github.com/dailephd/my-dev-kit-lab', kind: 'repository', external: true },
          { id: 'my-dev-kit-lab-module-package', label: 'npm', href: 'https://www.npmjs.com/package/@dailephd/my-dev-kit-lab', kind: 'package', external: true },
        ],
        versionRoadmap: [
          { state: 'recent', version: '0.6.1', description: 'Added affected-neighborhood experiment evidence for relating changed files and symbols to future task scope.' },
          { state: 'current', version: '0.6.2', description: 'Adds controlled incremental-change and staleness experiments comparing stale-index evidence with full refresh.' },
          { state: 'next', version: '0.6.3', description: 'Planned partial-refresh experiment treatments with explicit supported, unavailable, and simulated capability boundaries.' },
        ],
      },
    ],
  },
] as const satisfies readonly ProductFamily[];

export const productIndex = [
  {
    id: 'product-index-my-dev-kit',
    slug: 'my-dev-kit',
    itemType: 'product-family',
    title: 'my-dev-kit Ecosystem',
    summary: 'Static code context, staged workflow control, browser/runtime evidence, and optional assurance for coding-agent development.',
    positioning: 'Four local-first tools for building, checking, and improving disciplined AI-assisted software workflows.',
    status: 'active',
    category: 'developer-tooling',
    featured: true,
    displayPriority: 10,
    detailHref: '/projects/my-dev-kit',
    roadmapSlug: 'my-dev-kit',
    links: [],
  },
  {
    id: 'product-index-biolit',
    slug: 'biolit',
    itemType: 'standalone-product',
    title: 'BioLit',
    summary:
      'Scientific literature exploration software for organizing and reasoning over biomedical papers.',
    positioning: 'An experimental scientific-software workspace shaped by research workflows.',
    status: 'experimental',
    category: 'scientific-software',
    featured: false,
    displayPriority: 20,
    links: [],
  },
  {
    id: 'product-index-le-crawler',
    slug: 'le-crawler',
    itemType: 'standalone-product',
    title: 'Le Crawler',
    summary: "Chrome extension for controlled crawling of user-selected web content through the user's existing Chrome session, with structured local archiving and derived output.",
    positioning: 'Background, resumable web crawling with explicit scope, durable state, safety boundaries, and user-controlled local output.',
    status: 'in-development',
    category: 'developer-tooling',
    featured: false,
    displayPriority: 30,
    links: [],
  },
  {
    id: 'product-index-iworkhere-space',
    slug: 'iworkhere-space',
    itemType: 'standalone-product',
    title: 'iworkhere.space',
    summary: 'A collection of client-side utility tools built as an offline-capable Progressive Web App.',
    positioning: 'A registry-driven utility platform built with Next.js, React, and TypeScript, designed to grow through modular tool registration, automated testing, and offline support.',
    status: 'in-development',
    category: 'developer-tooling',
    featured: false,
    displayPriority: 40,
    links: [],
  },
] as const satisfies readonly ProductIndexItem[];
