import type { Publication } from '@/types/publication';

export const publications: Publication[] = [
  {
    id: 'dev-2026-efflux-rebinding',
    title: 'Efflux pumps control intracellular drug-target kinetics by limiting rebinding in bacteria',
    authors: [
      { name: 'Subrata Dev' },
      { name: 'Keiran Stevenson' },
      { name: 'Dai Le', isProfileOwner: true },
      { name: 'Minsu Kim' },
    ],
    year: 2026,
    journal: 'Science Advances',
    volume: 12,
    issue: 5,
    pages: 'eaea7983',
    doi: '10.1126/sciadv.aea7983',
    url: 'https://doi.org/10.1126/sciadv.aea7983',
    publisher: 'American Association for the Advancement of Science',
    abstract:
      'Bacterial efflux pumps are major contributors to multidrug resistance, classically described as “gatekeepers” that reduce drug entry. Here, we uncover a post–entry mechanism of efflux pumps, revealing their function deep into intracellular drug-target interactions. Using quantitative live-cell imaging, we monitored the activity of major efflux systems in Escherichia coli and Pseudomonas aeruginosa with Hoechst 33342 (HCT), a DNA binding inhibitor. We found that inactivation of efflux (ΔtolC in E. coli and Δ6 in P. aeruginosa) increased the apparent HCT-DNA affinity, mediated by a decreased apparent unbinding rate, whereas the intrinsic rate remained unchanged. Statistical physics modeling and experimental testing show that, unlike under dilute in vitro conditions, drug molecules that unbind from their targets in intracellular environments undergo successive rebinding, prolonging the total lifetime of the drug bound to the target. However, efflux pumps counteract this effect by suppressing rebinding, thereby kinetically destabilizing drug-target interactions. This biophysical mechanism acts multiplicatively with the canonical gatekeeping effect to broaden and amplify drug resistance.',
    formattedCitation:
      'Dev, S., Stevenson, K., Le, D., and Kim, M. Efflux pumps control intracellular drug-target kinetics by limiting rebinding in bacteria. Science Advances 12, 5, eaea7983 (2026). https://doi.org/10.1126/sciadv.aea7983',
    bibtex: `@article{dev2026efflux,
  title={Efflux pumps control intracellular drug-target kinetics by limiting rebinding in bacteria},
  author={Dev, Subrata and Stevenson, Keiran and Le, Dai and Kim, Minsu},
  journal={Science Advances},
  volume={12},
  number={5},
  pages={eaea7983},
  year={2026},
  publisher={American Association for the Advancement of Science},
  doi={10.1126/sciadv.aea7983},
  url={https://doi.org/10.1126/sciadv.aea7983}
}`,
    type: 'journal-article',
    links: [{ kind: 'doi', label: 'doi:10.1126/sciadv.aea7983', href: 'https://doi.org/10.1126/sciadv.aea7983' }],
    tags: ['Efflux pumps', 'Drug-target kinetics', 'Antibiotic resistance', 'Bacterial physiology'],
    displayPriority: 10,
    featured: true,
  },
  {
    id: 'le-2023-dissociation-kinetics',
    title: 'Dissociation kinetics of small-molecule inhibitors in Escherichia coli is coupled to physiological state of cells',
    authors: [
      { name: 'Dai Le', isProfileOwner: true },
      { name: 'Tatsuya Akiyama' },
      { name: 'David Weiss' },
      { name: 'Minsu Kim' },
    ],
    year: 2023,
    journal: 'Communications Biology',
    volume: 6,
    articleNumber: '223',
    doi: '10.1038/s42003-023-04604-9',
    url: 'https://doi.org/10.1038/s42003-023-04604-9',
    publisher: 'Springer Nature',
    abstract:
      'Bioactive small-molecule inhibitors represent a treasure chest for future drugs. In vitro high-throughput screening is a common approach to identify the small-molecule inhibitors that bind tightly to purified targets. Here, we investigate the inhibitor-target binding/unbinding kinetics in E. coli cells using a benzimidazole-derivative DNA inhibitor as a model system. We find that its unbinding rate is not constant but depends on cell growth rate. This dependence is mediated by the cellular activity, forming a feedback loop with the inhibitor\'s activity. In accordance with this feedback, we find cell-to-cell heterogeneity in inhibitor-target interaction, leading to co-existence of two distinct subpopulations: actively growing cells that dissociate the inhibitors from the targets and non-growing cells that do not. We find similar heterogeneity for other clinical DNA inhibitors. Our studies reveal a mechanism that couples inhibitor-target kinetics to cell physiology and demonstrate the significant effect of this coupling on drug efficacy.',
    formattedCitation:
      'Le, D., Akiyama, T., Weiss, D. et al. Dissociation kinetics of small-molecule inhibitors in Escherichia coli is coupled to physiological state of cells. Commun Biol 6, 223 (2023). https://doi.org/10.1038/s42003-023-04604-9',
    bibtex: `@article{le2023dissociation,
  title={Dissociation kinetics of small-molecule inhibitors in Escherichia coli is coupled to physiological state of cells},
  author={Le, Dai and Akiyama, Tatsuya and Weiss, David and Kim, Minsu},
  journal={Communications Biology},
  volume={6},
  pages={223},
  year={2023},
  publisher={Springer Nature},
  doi={10.1038/s42003-023-04604-9},
  url={https://doi.org/10.1038/s42003-023-04604-9}
}`,
    type: 'journal-article',
    links: [{ kind: 'doi', label: 'doi:10.1038/s42003-023-04604-9', href: 'https://doi.org/10.1038/s42003-023-04604-9' }],
    tags: ['Drug-target kinetics', 'Bacterial physiology', 'Small-molecule inhibitors'],
    displayPriority: 10,
    featured: true,
  },
  {
    id: 'le-2021-protonophores-efflux',
    title: 'Active Efflux Leads to Heterogeneous Dissipation of Proton Motive Force by Protonophores in Bacteria',
    authors: [
      { name: 'Dai Le', isProfileOwner: true },
      { name: 'Ekaterina Krasnopeeva' },
      { name: 'Faris Sinjab' },
      { name: 'Teuta Pilizota' },
      { name: 'Minsu Kim' },
    ],
    year: 2021,
    month: 'aug',
    journal: 'mBio',
    volume: 12,
    issue: 4,
    doi: '10.1128/mbio.00676-21',
    url: 'https://doi.org/10.1128/mbio.00676-21',
    publisher: 'American Society for Microbiology',
    abstract:
      'Various toxic compounds disrupt bacterial physiology. While bacteria harbor defense mechanisms to mitigate the toxicity, these mechanisms are often coupled to the physiological state of the cells and become ineffective when the physiology is severely disrupted. Here, we characterized such feedback by exposing Escherichia coli to protonophores. Protonophores dissipate the proton motive force (PMF), a fundamental force that drives physiological functions. We found that E. coli cells responded to protonophores heterogeneously, resulting in bimodal distributions of cell growth, substrate transport, and motility. Furthermore, we showed that this heterogeneous response required active efflux systems. The analysis of underlying interactions indicated the heterogeneous response results from efflux-mediated positive feedback between PMF and protonophores\' action. Our studies have broad implications for bacterial adaptation to stress, including antibiotics.\n\nIMPORTANCE An electrochemical proton gradient across the cytoplasmic membrane, alternatively known as proton motive force, energizes vital cellular processes in bacteria, including ATP synthesis, nutrient uptake, and cell division. Therefore, a wide range of organisms produce the agents that collapse the proton motive force, protonophores, to gain a competitive advantage. Studies have shown that protonophores have significant effects on microbial competition, host-pathogen interaction, and antibiotic action and resistance. Furthermore, protonophores are extensively used in various laboratory studies to perturb bacterial physiology. Here, we have characterized cell growth, substrate transport, and motility of Escherichia coli cells exposed to protonophores. Our findings demonstrate heterogeneous effects of protonophores on cell physiology and the underlying mechanism.',
    formattedCitation:
      'Le, D., Krasnopeeva, E., Sinjab, F., Pilizota, T., and Kim, M. Active Efflux Leads to Heterogeneous Dissipation of Proton Motive Force by Protonophores in Bacteria. mBio 12, 4 (2021). https://doi.org/10.1128/mbio.00676-21',
    bibtex: `@article{Le_2021,
  doi = {10.1128/mbio.00676-21},
  url = {https://doi.org/10.1128%2Fmbio.00676-21},
  year = 2021,
  month = {aug},
  publisher = {American Society for Microbiology},
  volume = {12},
  number = {4},
  author = {Dai Le and Ekaterina Krasnopeeva and Faris Sinjab and Teuta Pilizota and Minsu Kim},
  editor = {Vaughn S. Cooper},
  title = {Active Efflux Leads to Heterogeneous Dissipation of Proton Motive Force by Protonophores in Bacteria},
  journal = {{mBio}}
}`,
    type: 'journal-article',
    links: [{ kind: 'doi', label: 'doi:10.1128/mbio.00676-21', href: 'https://doi.org/10.1128/mbio.00676-21' }],
    tags: ['Proton motive force', 'Efflux pumps', 'Bacterial physiology', 'Protonophores'],
    displayPriority: 10,
    featured: false,
  },
  {
    id: 'le-2021-tsg101-rpe-polarity',
    title: 'Tsg101 is necessary for the establishment and maintenance of mouse retinal pigment epithelial cell polarity',
    authors: [
      { name: 'Dai Le', isProfileOwner: true },
      { name: 'Soyeon Lim' },
      { name: 'Kwang Wook Min' },
      { name: 'Joon Woo Park' },
      { name: 'Youjoung Kim' },
      { name: 'Taejeong Ha' },
      { name: 'Kyeong Hwan Moon' },
      { name: 'Kay-Uwe Wagner' },
      { name: 'Jin Woo Kim' },
    ],
    year: 2021,
    journal: 'Molecules and Cells',
    volume: 44,
    issue: 3,
    pages: '168-178',
    doi: '10.14348/molcells.2021.0027',
    url: 'https://doi.org/10.14348/molcells.2021.0027',
    publisher: 'Elsevier',
    abstract:
      'The retinal pigment epithelium (RPE) forms a monolayer sheet separating the retina and choroid in vertebrate eyes. The polarized nature of RPE is maintained by distributing membrane proteins differentially along apico-basal axis. We found the distributions of these proteins differ in embryonic, post-natal, and mature mouse RPE, suggesting developmental regulation of protein trafficking. Thus, we deleted tumor susceptibility gene 101 (Tsg101), a key component of endosomal sorting complexes required for transport (ESCRT), in embryonic and mature RPE to determine whether ESCRT-mediated endocytic protein trafficking correlated with the establishment and maintenance of RPE polarity. Loss of Tsg101 severely disturbed the polarity of RPE, which forms irregular aggregates exhibiting non-polarized distribution of cell adhesion proteins and activation of epidermal growth factor receptor signaling. These findings suggest that ESCRT-mediated protein trafficking is essential for the development and maintenance of RPE cell polarity.',
    formattedCitation:
      'Le, D., Lim, S., Min, K. W., Park, J. W., Kim, Y., Ha, T., Moon, K. H., Wagner, K.-U., and Kim, J. W. Tsg101 is necessary for the establishment and maintenance of mouse retinal pigment epithelial cell polarity. Molecules and Cells 44, 3, 168-178 (2021). https://doi.org/10.14348/molcells.2021.0027',
    bibtex: `@article{le2021tsg101,
  title={Tsg101 is necessary for the establishment and maintenance of mouse retinal pigment epithelial cell polarity},
  author={Le, Dai and Lim, Soyeon and Min, Kwang Wook and Park, Joon Woo and Kim, Youjoung and Ha, Taejeong and Moon, Kyeong Hwan and Wagner, Kay-Uwe and Kim, Jin Woo},
  journal={Molecules and Cells},
  volume={44},
  number={3},
  pages={168--178},
  year={2021},
  publisher={Elsevier},
  doi={10.14348/molcells.2021.0027},
  url={https://doi.org/10.14348/molcells.2021.0027}
}`,
    type: 'journal-article',
    links: [{ kind: 'doi', label: 'doi:10.14348/molcells.2021.0027', href: 'https://doi.org/10.14348/molcells.2021.0027' }],
    tags: ['Retinal pigment epithelium', 'Cell polarity', 'ESCRT', 'Retinal developmental biology'],
    displayPriority: 20,
    featured: false,
  },
  {
    id: 'iyer-2018-starvation-transcription-translation',
    title: 'Distinct mechanisms coordinate transcription and translation under carbon and nitrogen starvation in Escherichia coli',
    authors: [
      { name: 'Sukanya Iyer' },
      { name: 'Dai Le', isProfileOwner: true },
      { name: 'Bo Ryoung Park' },
      { name: 'Minsu Kim' },
    ],
    year: 2018,
    month: 'may',
    journal: 'Nature Microbiology',
    volume: 3,
    issue: 6,
    pages: '741-748',
    doi: '10.1038/s41564-018-0161-3',
    url: 'https://doi.org/10.1038/s41564-018-0161-3',
    publisher: 'Springer Science and Business Media LLC',
    abstract:
      'Bacteria adapt to environmental stress by producing proteins that provide stress protection. However, stress can severely perturb the kinetics of gene expression, disrupting protein production. Here, we characterized how Escherichia coli mitigates such perturbations under nutrient stress through the kinetic coordination of transcription and translation. We observed that, when translation became limiting under nitrogen starvation, transcription elongation slowed accordingly. This slowdown was mediated by (p)ppGpp, the alarmone whose primary role is thought to be promoter regulation. This kinetic coordination by (p)ppGpp was critical for the robust synthesis of gene products. Surprisingly, under carbon starvation, (p)ppGpp was dispensable for robust synthesis. Characterization of the underlying kinetics revealed that under carbon starvation, transcription became limiting, and translation aided transcription elongation. This mechanism naturally coordinated transcription with translation, alleviating the need for (p)ppGpp as a mediator. These contrasting mechanisms for coordination resulted in the condition-dependent effects of (p)ppGpp on global protein synthesis and starvation survival. Our findings reveal a kinetic aspect of gene expression plasticity, establishing (p)ppGpp as a condition-dependent global effector of gene expression.',
    formattedCitation:
      'Iyer, S., Le, D., Park, B. R., and Kim, M. Distinct mechanisms coordinate transcription and translation under carbon and nitrogen starvation in Escherichia coli. Nature Microbiology 3, 6, 741-748 (2018). https://doi.org/10.1038/s41564-018-0161-3',
    bibtex: `@article{Iyer_2018,
  doi = {10.1038/s41564-018-0161-3},
  url = {https://doi.org/10.1038%2Fs41564-018-0161-3},
  year = 2018,
  month = {may},
  publisher = {Springer Science and Business Media {LLC}},
  volume = {3},
  number = {6},
  pages = {741--748},
  author = {Sukanya Iyer and Dai Le and Bo Ryoung Park and Minsu Kim},
  title = {Distinct mechanisms coordinate transcription and translation under carbon and nitrogen starvation in Escherichia coli},
  journal = {Nature Microbiology}
}`,
    type: 'journal-article',
    links: [{ kind: 'doi', label: 'doi:10.1038/s41564-018-0161-3', href: 'https://doi.org/10.1038/s41564-018-0161-3' }],
    tags: ['Gene expression', 'Starvation response', 'Transcription', 'Translation', 'Bacterial physiology'],
    displayPriority: 10,
    featured: false,
  },
  {
    id: 'coates-2018-stochastic-clearance',
    title: 'Antibiotic-induced population fluctuations and stochastic clearance of bacteria',
    authors: [
      { name: 'Jessica Coates' },
      { name: 'Bo Ryoung Park' },
      { name: 'Dai Le', isProfileOwner: true },
      { name: 'Emrah Simsek' },
      { name: 'Waqas Chaudhry' },
      { name: 'Minsu Kim' },
    ],
    year: 2018,
    month: 'mar',
    journal: 'eLife',
    volume: 7,
    doi: '10.7554/elife.32976',
    url: 'https://doi.org/10.7554/elife.32976',
    publisher: 'eLife Sciences Publications, Ltd',
    abstract:
      'Effective antibiotic use that minimizes treatment failures remains a challenge. A better understanding of how bacterial populations respond to antibiotics is necessary. Previous studies of large bacterial populations established the deterministic framework of pharmacodynamics. Here, characterizing the dynamics of population extinction, we demonstrated the stochastic nature of eradicating bacteria with antibiotics. Antibiotics known to kill bacteria (bactericidal) induced population fluctuations. Thus, at high antibiotic concentrations, the dynamics of bacterial clearance were heterogeneous. At low concentrations, clearance still occurred with a non-zero probability. These striking outcomes of population fluctuations were well captured by our probabilistic model. Our model further suggested a strategy to facilitate eradication by increasing extinction probability. We experimentally tested this prediction for antibiotic-susceptible and clinically-isolated resistant bacteria. This new knowledge exposes fundamental limits in our ability to predict bacterial eradication. Additionally, it demonstrates the potential of using antibiotic concentrations that were previously deemed inefficacious to eradicate bacteria.',
    formattedCitation:
      'Coates, J., Park, B. R., Le, D., Simsek, E., Chaudhry, W., and Kim, M. Antibiotic-induced population fluctuations and stochastic clearance of bacteria. eLife 7 (2018). https://doi.org/10.7554/elife.32976',
    bibtex: `@article{Coates_2018,
  doi = {10.7554/elife.32976},
  url = {https://doi.org/10.7554%2Felife.32976},
  year = 2018,
  month = {mar},
  publisher = {{eLife} Sciences Publications, Ltd},
  volume = {7},
  author = {Jessica Coates and Bo Ryoung Park and Dai Le and Emrah {\\c{S}}im{\\c{s}}ek and Waqas Chaudhry and Minsu Kim},
  title = {Antibiotic-induced population fluctuations and stochastic clearance of bacteria},
  journal = {{eLife}}
}`,
    type: 'journal-article',
    links: [{ kind: 'doi', label: 'doi:10.7554/elife.32976', href: 'https://doi.org/10.7554/elife.32976' }],
    tags: ['Antibiotic resistance', 'Bacterial population dynamics', 'Stochastic clearance'],
    displayPriority: 20,
    featured: false,
  },
  {
    id: 'ha-2017-rpe-notch',
    title: 'The Retinal Pigment Epithelium Is a Notch Signaling Niche in the Mouse Retina',
    authors: [
      { name: 'Taejeong Ha' },
      { name: 'Kyeong Hwan Moon' },
      { name: 'Le Dai', isProfileOwner: true },
      { name: 'Jun Hatakeyama' },
      { name: 'Keejung Yoon' },
      { name: 'Hee-Sae Park' },
      { name: 'Young-Yoon Kong' },
      { name: 'Kenji Shimamura' },
      { name: 'Jin Woo Kim' },
    ],
    year: 2017,
    month: 'apr',
    journal: 'Cell Reports',
    volume: 19,
    issue: 2,
    pages: '351-363',
    doi: '10.1016/j.celrep.2017.03.040',
    url: 'https://doi.org/10.1016/j.celrep.2017.03.040',
    publisher: 'Elsevier BV',
    abstract:
      'Notch signaling in neural progenitor cell is triggered by ligands expressed in adjacent cells. To identify the sources of active Notch ligands in the mouse retina, we negatively regulated Notch ligand activity in various neighbors of retinal progenitor cells (RPCs) by eliminating mindbomb E3 ubiquitin protein ligase 1 (Mib1). Mib1-deficient retinal cells failed to induce Notch activation in intra-lineage RPCs, which prematurely differentiated into neurons; however, Mib1 in post-mitotic retinal ganglion cells was not important. Interestingly, Mib1 in the retinal pigment epithelium (RPE) also contributed to Notch activation in adjacent RPCs by supporting the localization of active Notch ligands at RPE-RPC contacts. Combining this RPE-driven Notch signaling and intra-retinal Notch signaling, we propose a model in which one RPC daughter receives extra Notch signals from the RPE to become an RPC, whereas its sister cell receives only a subthreshold level of intra-retinal Notch signal and differentiates into a neuron.',
    formattedCitation:
      'Ha, T., Moon, K. H., Dai, L., Hatakeyama, J., Yoon, K., Park, H.-S., Kong, Y.-Y., Shimamura, K., and Kim, J. W. The Retinal Pigment Epithelium Is a Notch Signaling Niche in the Mouse Retina. Cell Reports 19, 2, 351-363 (2017). https://doi.org/10.1016/j.celrep.2017.03.040',
    bibtex: `@article{Ha_2017,
  doi = {10.1016/j.celrep.2017.03.040},
  url = {https://doi.org/10.1016%2Fj.celrep.2017.03.040},
  year = 2017,
  month = {apr},
  publisher = {Elsevier {BV}},
  volume = {19},
  number = {2},
  pages = {351--363},
  author = {Taejeong Ha and Kyeong Hwan Moon and Le Dai and Jun Hatakeyama and Keejung Yoon and Hee-Sae Park and Young-Yoon Kong and Kenji Shimamura and Jin Woo Kim},
  title = {The Retinal Pigment Epithelium Is a Notch Signaling Niche in the Mouse Retina},
  journal = {Cell Reports}
}`,
    type: 'journal-article',
    links: [{ kind: 'doi', label: 'doi:10.1016/j.celrep.2017.03.040', href: 'https://doi.org/10.1016/j.celrep.2017.03.040' }],
    tags: ['Notch signaling', 'Retinal pigment epithelium', 'Retinal developmental biology'],
    displayPriority: 10,
    featured: false,
  },
  {
    id: 'kim-2014-vax1-retinal-axon-growth',
    title: 'Regulation of retinal axon growth by secreted Vax1 homeodomain protein',
    authors: [
      { name: 'Namsuk Kim' },
      { name: 'Kwang Wook Min' },
      { name: 'Kyung Hwa Kang' },
      { name: 'Eun Jung Lee' },
      { name: 'Hyoung-Tai Kim' },
      { name: 'Kyunghwan Moon' },
      { name: 'Jiheon Choi' },
      { name: 'Dai Le', isProfileOwner: true },
      { name: 'Sang-Hee Lee' },
      { name: 'Jin Woo Kim' },
    ],
    year: 2014,
    month: 'sep',
    journal: 'eLife',
    volume: 3,
    doi: '10.7554/elife.02671',
    url: 'https://doi.org/10.7554/elife.02671',
    publisher: 'eLife Sciences Publications, Ltd',
    abstract:
      'Retinal ganglion cell (RGC) axons of binocular animals cross the midline at the optic chiasm (OC) to grow toward their synaptic targets in the contralateral brain. Ventral anterior homeobox 1 (Vax1) plays an essential role in the development of the OC by regulating RGC axon growth in a non-cell autonomous manner. In this study, we identify an unexpected function of Vax1 that is secreted from ventral hypothalamic cells and diffuses to RGC axons, where it promotes axonal growth independent of its transcription factor activity. We demonstrate that Vax1 binds to extracellular sugar groups of the heparan sulfate proteoglycans (HSPGs) located in RGC axons. Both Vax1 binding to HSPGs and subsequent penetration into the axoplasm, where Vax1 activates local protein synthesis, are required for RGC axonal growth. Together, our findings demonstrate that Vax1 possesses a novel RGC axon growth factor activity that is critical for the development of the mammalian binocular visual system.',
    formattedCitation:
      'Kim, N., Min, K. W., Kang, K. H., Lee, E. J., Kim, H.-T., Moon, K., Choi, J., Le, D., Lee, S.-H., and Kim, J. W. Regulation of retinal axon growth by secreted Vax1 homeodomain protein. eLife 3 (2014). https://doi.org/10.7554/elife.02671',
    bibtex: `@article{Kim_2014,
  doi = {10.7554/elife.02671},
  url = {https://doi.org/10.7554%2Felife.02671},
  year = 2014,
  month = {sep},
  publisher = {{eLife} Sciences Publications, Ltd},
  volume = {3},
  author = {Namsuk Kim and Kwang Wook Min and Kyung Hwa Kang and Eun Jung Lee and Hyoung-Tai Kim and Kyunghwan Moon and Jiheon Choi and Dai Le and Sang-Hee Lee and Jin Woo Kim},
  title = {Regulation of retinal axon growth by secreted Vax1 homeodomain protein},
  journal = {{eLife}}
}`,
    type: 'journal-article',
    links: [{ kind: 'doi', label: 'doi:10.7554/elife.02671', href: 'https://doi.org/10.7554/elife.02671' }],
    tags: ['Retinal axon growth', 'Vax1', 'Retinal developmental biology', 'Homeodomain protein'],
    displayPriority: 10,
    featured: false,
  },
];
