import type { Roadmap } from '@/types/roadmap';

export const roadmaps: readonly Roadmap[] = [
  {
    id: 'my-dev-kit-ecosystem-roadmap',
    slug: 'my-dev-kit',
    title: 'my-dev-kit Ecosystem Roadmap',
    shortTitle: 'Ecosystem roadmap',
    productSlug: 'my-dev-kit',
    summary: 'Current and next milestones across static repository evidence, workflow control, runtime evidence, and optional assurance.',
    status: 'active',
    updatedAt: '2026-09-29',
    featured: true,
    displayPriority: 10,
    lanes: [
      {
        id: 'roadmap-lane-my-dev-kit',
        title: 'my-dev-kit',
        roleLabel: 'Codebase Intelligence',
        summary: 'Static repository evidence, graph-guided retrieval, and bounded context preparation.',
        moduleSlug: 'my-dev-kit',
        status: 'active',
        displayPriority: 10,
        phases: [
          {
            id: 'mdk-affected-neighborhood',
            title: 'Affected-neighborhood incremental refresh',
            status: 'shipped',
            timeframe: 'Current · 1.12.5',
            priority: 'now',
            summary: 'Refresh otherwise-unchanged files in a trusted one-hop affected neighborhood while preserving truthful fallback behavior.',
            displayPriority: 10,
            milestones: [
              { id: 'mdk-trusted-baseline', title: 'Trusted baseline selection', status: 'shipped', summary: 'Use compatible prior index evidence or fail safely to a full rebuild.', links: [], displayPriority: 10 },
              { id: 'mdk-refresh-scope', title: 'Explicit refresh-scope evidence', status: 'shipped', summary: 'Report requested and applied incremental refresh behavior without silently degrading semantics.', links: [], displayPriority: 20 },
            ],
          },
          {
            id: 'mdk-android-benchmarks',
            title: 'Android retrieval benchmarks and examples',
            status: 'planned',
            timeframe: 'Next · 1.13.0',
            priority: 'next',
            summary: 'Make Android retrieval support testable and repeatable through benchmark tasks, fixtures, examples, and workflow guidance.',
            displayPriority: 20,
            milestones: [
              { id: 'mdk-android-coverage', title: 'Android benchmark coverage', status: 'planned', summary: 'Exercise Compose, ViewModel, repository, Room, Retrofit, manifest, resource, navigation, and Android-test retrieval.', links: [], displayPriority: 10 },
              { id: 'mdk-android-examples', title: 'Android examples and workflow documentation', status: 'planned', summary: 'Provide repeatable Android indexing, command, wrong-layer, and coding-agent workflow examples.', links: [], displayPriority: 20 },
            ],
          },
        ],
      },
      {
        id: 'roadmap-lane-orchestrator',
        title: 'my-dev-kit-orchestrator',
        roleLabel: 'Workflow Orchestration',
        summary: 'Staged prompts, lifecycle integrity, readiness, responsibility continuity, correction routing, and handoff.',
        moduleSlug: 'my-dev-kit-orchestrator',
        status: 'active',
        displayPriority: 20,
        phases: [
          {
            id: 'orchestrator-economics',
            title: 'Workflow telemetry and economics',
            status: 'shipped',
            timeframe: 'Current · 1.6.0',
            priority: 'now',
            summary: 'Record bounded native run observations and derive deterministic Orchestrator workflow-economics evidence without changing lifecycle decisions.',
            displayPriority: 10,
            milestones: [
              { id: 'orchestrator-observations', title: 'Versioned run observations', status: 'shipped', summary: 'Record bounded observations for native start, prompt, and mark activity.', links: [], displayPriority: 10 },
              { id: 'orchestrator-deterministic-economics', title: 'Deterministic Workflow Economics', status: 'shipped', summary: 'Derive inspectable Orchestrator-owned workflow activity while keeping unavailable facts explicitly unavailable.', links: [], displayPriority: 20 },
            ],
          },
          {
            id: 'orchestrator-evidence-intake',
            title: 'Generic ecosystem evidence intake',
            status: 'planned',
            timeframe: 'Next · 1.7.0',
            priority: 'next',
            summary: "Consume typed ecosystem evidence references while preserving each producer's native contracts and the existing integrity owners.",
            displayPriority: 20,
            milestones: [
              { id: 'orchestrator-evidence-references', title: 'Typed evidence requirements and references', status: 'planned', summary: 'Accept supported evidence requirements and native artifact references without copying all producer data into Orchestrator.', links: [], displayPriority: 10 },
              { id: 'orchestrator-freshness', title: 'Compatibility and freshness integration', status: 'planned', summary: 'Carry supported evidence state through prompt, mark, check, status, export, and correction without bypassing run integrity.', links: [], displayPriority: 20 },
            ],
          },
        ],
      },
      {
        id: 'roadmap-lane-observer',
        title: 'my-frontend-observer',
        roleLabel: 'Runtime Evidence',
        summary: 'Rendered browser evidence, comparisons, frontend contracts, references, annotation, and visual correction workflows.',
        moduleSlug: 'my-frontend-observer',
        status: 'active',
        displayPriority: 30,
        phases: [
          {
            id: 'observer-visual-workflow',
            title: 'Full visual frontend-change workflow',
            status: 'shipped',
            timeframe: 'Current · 0.10.0',
            priority: 'now',
            summary: 'Combine actual frontend captures or approved visual references with contracts, correction evidence, viewer review, and explicit acceptance.',
            displayPriority: 10,
            milestones: [
              { id: 'observer-capture-check-view', title: 'Project-aware capture, check, and view', status: 'shipped', summary: 'Use managed runtime evidence and aliases for baseline capture, candidate checking, and local inspection.', links: [], displayPriority: 10 },
              { id: 'observer-contracts-references', title: 'Contracts, references, annotation, and correction', status: 'shipped', summary: 'Preserve protected behavior while supporting explicit visual intent, reference fidelity, correction evidence, and human approval.', links: [], displayPriority: 20 },
            ],
          },
          {
            id: 'observer-diagnostics',
            title: 'Bounded runtime diagnostics',
            status: 'planned',
            timeframe: 'Next · 0.11.0',
            priority: 'next',
            summary: 'Explain browser/runtime failures with bounded diagnostic evidence instead of screenshots or generic errors alone.',
            displayPriority: 20,
            milestones: [
              { id: 'observer-console-errors', title: 'Console and page-error evidence', status: 'planned', summary: 'Capture bounded, redacted console and page-error evidence with deterministic provenance.', links: [], displayPriority: 10 },
              { id: 'observer-network-errors', title: 'Network failure and HTTP status evidence', status: 'planned', summary: 'Distinguish request transport failures from HTTP response-status evidence without creating a general network recorder.', links: [], displayPriority: 20 },
            ],
          },
        ],
      },
      {
        id: 'roadmap-lane-lab',
        title: 'my-dev-kit-lab',
        roleLabel: 'Validation Lab',
        summary: 'Optional experiments, audits, security validation, benchmarks, and reviewable evidence.',
        moduleSlug: 'my-dev-kit-lab',
        status: 'active',
        displayPriority: 40,
        phases: [
          {
            id: 'lab-staleness-experiments',
            title: 'Incremental-change and staleness experiments',
            status: 'shipped',
            timeframe: 'Current · 0.6.2',
            priority: 'now',
            summary: 'Compare stale baseline retrieval with full post-change refresh after deterministic controlled changes.',
            displayPriority: 10,
            milestones: [
              { id: 'lab-stale-comparison', title: 'Controlled stale-index comparison', status: 'shipped', summary: 'Run matched stale-index and full-refresh treatments against frozen controlled-change scenarios.', links: [], displayPriority: 10 },
              { id: 'lab-stale-risk', title: 'Conservative stale-risk evidence', status: 'shipped', summary: 'Report observed regression, no observed regression, or inconclusive evidence without claiming general stale-index safety.', links: [], displayPriority: 20 },
            ],
          },
          {
            id: 'lab-partial-refresh',
            title: 'Partial-refresh planning',
            status: 'planned',
            timeframe: 'Next · 0.6.3',
            priority: 'next',
            summary: 'Model bounded refresh treatments while clearly separating supported upstream behavior from unavailable or simulated evidence.',
            displayPriority: 20,
            milestones: [
              { id: 'lab-refresh-treatments', title: 'Refresh treatment model', status: 'planned', summary: 'Represent full refresh, no refresh, changed-files refresh, and affected-neighborhood refresh treatments explicitly.', links: [], displayPriority: 10 },
              { id: 'lab-capability-boundary', title: 'Capability-boundary reporting', status: 'planned', summary: 'Keep unsupported, unavailable, unknown, and inconclusive refresh evidence explicit rather than fabricating successful support.', links: [], displayPriority: 20 },
            ],
          },
        ],
      },
    ],
  },
] as const;
